### ISSUE TITLE
Track: Module 7

### ISSUE THREAD

**Issue by sortedcord** [sortedcord/vue-notes#11]
# Vue CLI

- [ ] Introduction
- [ ] Why we need a dev server
- [ ] Installing vue CLI
- [ ] File inspection
- [ ] Inspecting vue code and .vue
- [ ] The Vetur Extension
- [ ] Basic vue app
- [ ] Adding Styling
