### ISSUE TITLE
Track: Module 2

### ISSUE THREAD

**Issue by sortedcord** [sortedcord/vue-notes#7]
<h2><strong> Learning Basics and Core Concepts </strong></h2>

- [x] Creating and Connecting Vue App Instances
- [x] Interpolation and Data Binding 
- [x] Binding Attributes with the v-bind
- [x] Understanding Methods
- [x] Working with Data inside of Vue
- [x] Ouputting Raw HTML code
- [x] Understanding Event Binding
- [x] Events and Methods
- [x] Using Native Event Object
- [x] Exploring Event Modifiers
- [x] Locking content with v-once
- [x] Data Binding + Event Binding
- [x] Methods used for data binding
- [x] Computed Properties
- [x] Working with watchers
- [x] Methods vs Computed Properties vs Watchers
- [x] Shorthands
- [x] Dynamic Styling 
- [x] Adding CSS Classes Dynamically
- [x] Classes and computed properites
- [x]  Dynamic Classes array syntax
