### ISSUE TITLE
Track: Module 3

### ISSUE THREAD

**Issue by sortedcord** [sortedcord/vue-notes#8]
<h2><strong>Rendering Conditional Content</strong></h2>

- [x] Rendering Content Conditionally
- [x] v-if, v-else
- [x] v-show
- [x] Rendering lists of data
- [x] v-for
- [x] Removing List items
- [x] Lists and Keys
